[package]
name = "hello-rust"
version = "1.0.0"
authors = ["pranaysaha <saha.pranay25@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1"
